version: '3.8'

services:
  app:
    build: .
    container_name: onstar-token-gen
    volumes:
      - .:/var/www/html
    expose:
      - "9000"

  nginx:
    image: nginx:alpine
    container_name: nginx-server
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
